package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tbcatalogopuntossilaba generated by hbm2java
 */
public class Tbcatalogopuntossilaba  implements java.io.Serializable {


     private Integer consecutivo;
     private String codigo;
     private String descripcion;
     private String fechaCreacion;
     private String usuarioCreacion;
     private Set<Tbexperienciapuntos> tbexperienciapuntoses = new HashSet<Tbexperienciapuntos>(0);
     private Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas = new HashSet<Tbcompetenciaspuntossilaba>(0);
     private Set<Tbsociospuntosilaba> tbsociospuntosilabas = new HashSet<Tbsociospuntosilaba>(0);
     private Set<Tbcontenidosilaber> tbcontenidosilabers = new HashSet<Tbcontenidosilaber>(0);

    public Tbcatalogopuntossilaba() {
    }

	
    public Tbcatalogopuntossilaba(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogopuntossilaba(Integer consecutivo, String codigo, String descripcion, String fechaCreacion, String usuarioCreacion, Set<Tbexperienciapuntos> tbexperienciapuntoses, Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas, Set<Tbsociospuntosilaba> tbsociospuntosilabas, Set<Tbcontenidosilaber> tbcontenidosilabers) {
       this.consecutivo = consecutivo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreacion = usuarioCreacion;
       this.tbexperienciapuntoses = tbexperienciapuntoses;
       this.tbcompetenciaspuntossilabas = tbcompetenciaspuntossilabas;
       this.tbsociospuntosilabas = tbsociospuntosilabas;
       this.tbcontenidosilabers = tbcontenidosilabers;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    public Set<Tbexperienciapuntos> getTbexperienciapuntoses() {
        return this.tbexperienciapuntoses;
    }
    
    public void setTbexperienciapuntoses(Set<Tbexperienciapuntos> tbexperienciapuntoses) {
        this.tbexperienciapuntoses = tbexperienciapuntoses;
    }
    public Set<Tbcompetenciaspuntossilaba> getTbcompetenciaspuntossilabas() {
        return this.tbcompetenciaspuntossilabas;
    }
    
    public void setTbcompetenciaspuntossilabas(Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas) {
        this.tbcompetenciaspuntossilabas = tbcompetenciaspuntossilabas;
    }
    public Set<Tbsociospuntosilaba> getTbsociospuntosilabas() {
        return this.tbsociospuntosilabas;
    }
    
    public void setTbsociospuntosilabas(Set<Tbsociospuntosilaba> tbsociospuntosilabas) {
        this.tbsociospuntosilabas = tbsociospuntosilabas;
    }
    public Set<Tbcontenidosilaber> getTbcontenidosilabers() {
        return this.tbcontenidosilabers;
    }
    
    public void setTbcontenidosilabers(Set<Tbcontenidosilaber> tbcontenidosilabers) {
        this.tbcontenidosilabers = tbcontenidosilabers;
    }




}


