package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tbcatalogoareas generated by hbm2java
 */
public class Tbcatalogoareas  implements java.io.Serializable {


     private Integer consecutivo;
     private String codigo;
     private String descripcion;
     private String fechaCreacion;
     private String usuarioCreacion;
     private Set<Tbtemasareas> tbtemasareases = new HashSet<Tbtemasareas>(0);

    public Tbcatalogoareas() {
    }

	
    public Tbcatalogoareas(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogoareas(Integer consecutivo, String codigo, String descripcion, String fechaCreacion, String usuarioCreacion, Set<Tbtemasareas> tbtemasareases) {
       this.consecutivo = consecutivo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreacion = usuarioCreacion;
       this.tbtemasareases = tbtemasareases;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    public Set<Tbtemasareas> getTbtemasareases() {
        return this.tbtemasareases;
    }
    
    public void setTbtemasareases(Set<Tbtemasareas> tbtemasareases) {
        this.tbtemasareases = tbtemasareases;
    }




}


