package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tbcatalogocompetencias generated by hbm2java
 */
public class Tbcatalogocompetencias  implements java.io.Serializable {


     private Integer consecutivo;
     private String codigo;
     private String descripcion;
     private String fechaCreacion;
     private String usuarioCreacion;
     private Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas = new HashSet<Tbcompetenciaspuntossilaba>(0);
     private Set<Tbcompetenciasareas> tbcompetenciasareases = new HashSet<Tbcompetenciasareas>(0);

    public Tbcatalogocompetencias() {
    }

	
    public Tbcatalogocompetencias(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogocompetencias(Integer consecutivo, String codigo, String descripcion, String fechaCreacion, String usuarioCreacion, Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas, Set<Tbcompetenciasareas> tbcompetenciasareases) {
       this.consecutivo = consecutivo;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreacion = usuarioCreacion;
       this.tbcompetenciaspuntossilabas = tbcompetenciaspuntossilabas;
       this.tbcompetenciasareases = tbcompetenciasareases;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    public Set<Tbcompetenciaspuntossilaba> getTbcompetenciaspuntossilabas() {
        return this.tbcompetenciaspuntossilabas;
    }
    
    public void setTbcompetenciaspuntossilabas(Set<Tbcompetenciaspuntossilaba> tbcompetenciaspuntossilabas) {
        this.tbcompetenciaspuntossilabas = tbcompetenciaspuntossilabas;
    }
    public Set<Tbcompetenciasareas> getTbcompetenciasareases() {
        return this.tbcompetenciasareases;
    }
    
    public void setTbcompetenciasareases(Set<Tbcompetenciasareas> tbcompetenciasareases) {
        this.tbcompetenciasareases = tbcompetenciasareases;
    }




}


