package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tbcompetenciasareas generated by hbm2java
 */
public class Tbcompetenciasareas  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcatalogocompetencias tbcatalogocompetencias;
     private Tbtemasareas tbtemasareas;
     private Set<Tbmetasxniveleducativo> tbmetasxniveleducativos = new HashSet<Tbmetasxniveleducativo>(0);

    public Tbcompetenciasareas() {
    }

	
    public Tbcompetenciasareas(Integer consecutivo, Tbcatalogocompetencias tbcatalogocompetencias, Tbtemasareas tbtemasareas) {
        this.consecutivo = consecutivo;
        this.tbcatalogocompetencias = tbcatalogocompetencias;
        this.tbtemasareas = tbtemasareas;
    }
    public Tbcompetenciasareas(Integer consecutivo, Tbcatalogocompetencias tbcatalogocompetencias, Tbtemasareas tbtemasareas, Set<Tbmetasxniveleducativo> tbmetasxniveleducativos) {
       this.consecutivo = consecutivo;
       this.tbcatalogocompetencias = tbcatalogocompetencias;
       this.tbtemasareas = tbtemasareas;
       this.tbmetasxniveleducativos = tbmetasxniveleducativos;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogocompetencias getTbcatalogocompetencias() {
        return this.tbcatalogocompetencias;
    }
    
    public void setTbcatalogocompetencias(Tbcatalogocompetencias tbcatalogocompetencias) {
        this.tbcatalogocompetencias = tbcatalogocompetencias;
    }
    public Tbtemasareas getTbtemasareas() {
        return this.tbtemasareas;
    }
    
    public void setTbtemasareas(Tbtemasareas tbtemasareas) {
        this.tbtemasareas = tbtemasareas;
    }
    public Set<Tbmetasxniveleducativo> getTbmetasxniveleducativos() {
        return this.tbmetasxniveleducativos;
    }
    
    public void setTbmetasxniveleducativos(Set<Tbmetasxniveleducativo> tbmetasxniveleducativos) {
        this.tbmetasxniveleducativos = tbmetasxniveleducativos;
    }




}


