package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbcontenidosilaber generated by hbm2java
 */
public class Tbcontenidosilaber  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcatalogopuntossilaba tbcatalogopuntossilaba;
     private String descripcion;
     private String observacion;
     private Date fechaCreacion;
     private String usuarioCreacion;
     private String url;
     private Set<Tbprogramacionexperienciasilaber> tbprogramacionexperienciasilabers = new HashSet<Tbprogramacionexperienciasilaber>(0);

    public Tbcontenidosilaber() {
    }

	
    public Tbcontenidosilaber(Integer consecutivo, Tbcatalogopuntossilaba tbcatalogopuntossilaba) {
        this.consecutivo = consecutivo;
        this.tbcatalogopuntossilaba = tbcatalogopuntossilaba;
    }
    public Tbcontenidosilaber(Integer consecutivo, Tbcatalogopuntossilaba tbcatalogopuntossilaba, String descripcion, String observacion, Date fechaCreacion, String usuarioCreacion, String url, Set<Tbprogramacionexperienciasilaber> tbprogramacionexperienciasilabers) {
       this.consecutivo = consecutivo;
       this.tbcatalogopuntossilaba = tbcatalogopuntossilaba;
       this.descripcion = descripcion;
       this.observacion = observacion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreacion = usuarioCreacion;
       this.url = url;
       this.tbprogramacionexperienciasilabers = tbprogramacionexperienciasilabers;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogopuntossilaba getTbcatalogopuntossilaba() {
        return this.tbcatalogopuntossilaba;
    }
    
    public void setTbcatalogopuntossilaba(Tbcatalogopuntossilaba tbcatalogopuntossilaba) {
        this.tbcatalogopuntossilaba = tbcatalogopuntossilaba;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Set<Tbprogramacionexperienciasilaber> getTbprogramacionexperienciasilabers() {
        return this.tbprogramacionexperienciasilabers;
    }
    
    public void setTbprogramacionexperienciasilabers(Set<Tbprogramacionexperienciasilaber> tbprogramacionexperienciasilabers) {
        this.tbprogramacionexperienciasilabers = tbprogramacionexperienciasilabers;
    }




}


