package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final



/**
 * Tbestimulosdidacticossilaberxcompetencias generated by hbm2java
 */
public class Tbestimulosdidacticossilaberxcompetencias  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbelementosdidacticos tbelementosdidacticos;
     private Tbmapacompetenciassilaber tbmapacompetenciassilaber;

    public Tbestimulosdidacticossilaberxcompetencias() {
    }

    public Tbestimulosdidacticossilaberxcompetencias(Integer consecutivo, Tbelementosdidacticos tbelementosdidacticos, Tbmapacompetenciassilaber tbmapacompetenciassilaber) {
       this.consecutivo = consecutivo;
       this.tbelementosdidacticos = tbelementosdidacticos;
       this.tbmapacompetenciassilaber = tbmapacompetenciassilaber;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbelementosdidacticos getTbelementosdidacticos() {
        return this.tbelementosdidacticos;
    }
    
    public void setTbelementosdidacticos(Tbelementosdidacticos tbelementosdidacticos) {
        this.tbelementosdidacticos = tbelementosdidacticos;
    }
    public Tbmapacompetenciassilaber getTbmapacompetenciassilaber() {
        return this.tbmapacompetenciassilaber;
    }
    
    public void setTbmapacompetenciassilaber(Tbmapacompetenciassilaber tbmapacompetenciassilaber) {
        this.tbmapacompetenciassilaber = tbmapacompetenciassilaber;
    }




}


