package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Tbmapacompetenciassilaber generated by hbm2java
 */
public class Tbmapacompetenciassilaber  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcompetenciaspuntossilaba tbcompetenciaspuntossilaba;
     private Tbprogramacionexperienciasilaber tbprogramacionexperienciasilaber;
     private Set<Tbestimulosdidacticossilaberxcompetencias> tbestimulosdidacticossilaberxcompetenciases = new HashSet<Tbestimulosdidacticossilaberxcompetencias>(0);

    public Tbmapacompetenciassilaber() {
    }

	
    public Tbmapacompetenciassilaber(Integer consecutivo, Tbcompetenciaspuntossilaba tbcompetenciaspuntossilaba, Tbprogramacionexperienciasilaber tbprogramacionexperienciasilaber) {
        this.consecutivo = consecutivo;
        this.tbcompetenciaspuntossilaba = tbcompetenciaspuntossilaba;
        this.tbprogramacionexperienciasilaber = tbprogramacionexperienciasilaber;
    }
    public Tbmapacompetenciassilaber(Integer consecutivo, Tbcompetenciaspuntossilaba tbcompetenciaspuntossilaba, Tbprogramacionexperienciasilaber tbprogramacionexperienciasilaber, Set<Tbestimulosdidacticossilaberxcompetencias> tbestimulosdidacticossilaberxcompetenciases) {
       this.consecutivo = consecutivo;
       this.tbcompetenciaspuntossilaba = tbcompetenciaspuntossilaba;
       this.tbprogramacionexperienciasilaber = tbprogramacionexperienciasilaber;
       this.tbestimulosdidacticossilaberxcompetenciases = tbestimulosdidacticossilaberxcompetenciases;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcompetenciaspuntossilaba getTbcompetenciaspuntossilaba() {
        return this.tbcompetenciaspuntossilaba;
    }
    
    public void setTbcompetenciaspuntossilaba(Tbcompetenciaspuntossilaba tbcompetenciaspuntossilaba) {
        this.tbcompetenciaspuntossilaba = tbcompetenciaspuntossilaba;
    }
    public Tbprogramacionexperienciasilaber getTbprogramacionexperienciasilaber() {
        return this.tbprogramacionexperienciasilaber;
    }
    
    public void setTbprogramacionexperienciasilaber(Tbprogramacionexperienciasilaber tbprogramacionexperienciasilaber) {
        this.tbprogramacionexperienciasilaber = tbprogramacionexperienciasilaber;
    }
    public Set<Tbestimulosdidacticossilaberxcompetencias> getTbestimulosdidacticossilaberxcompetenciases() {
        return this.tbestimulosdidacticossilaberxcompetenciases;
    }
    
    public void setTbestimulosdidacticossilaberxcompetenciases(Set<Tbestimulosdidacticossilaberxcompetencias> tbestimulosdidacticossilaberxcompetenciases) {
        this.tbestimulosdidacticossilaberxcompetenciases = tbestimulosdidacticossilaberxcompetenciases;
    }




}


