package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final



/**
 * Tbmetasxniveleducativo generated by hbm2java
 */
public class Tbmetasxniveleducativo  implements java.io.Serializable {


     private Integer cosecutivo;
     private Tbcompetenciasareas tbcompetenciasareas;
     private Tbniveleducativo tbniveleducativo;
     private Integer meta;

    public Tbmetasxniveleducativo() {
    }

	
    public Tbmetasxniveleducativo(Integer cosecutivo, Tbcompetenciasareas tbcompetenciasareas, Tbniveleducativo tbniveleducativo) {
        this.cosecutivo = cosecutivo;
        this.tbcompetenciasareas = tbcompetenciasareas;
        this.tbniveleducativo = tbniveleducativo;
    }
    public Tbmetasxniveleducativo(Integer cosecutivo, Tbcompetenciasareas tbcompetenciasareas, Tbniveleducativo tbniveleducativo, Integer meta) {
       this.cosecutivo = cosecutivo;
       this.tbcompetenciasareas = tbcompetenciasareas;
       this.tbniveleducativo = tbniveleducativo;
       this.meta = meta;
    }
   
    public Integer getCosecutivo() {
        return this.cosecutivo;
    }
    
    public void setCosecutivo(Integer cosecutivo) {
        this.cosecutivo = cosecutivo;
    }
    public Tbcompetenciasareas getTbcompetenciasareas() {
        return this.tbcompetenciasareas;
    }
    
    public void setTbcompetenciasareas(Tbcompetenciasareas tbcompetenciasareas) {
        this.tbcompetenciasareas = tbcompetenciasareas;
    }
    public Tbniveleducativo getTbniveleducativo() {
        return this.tbniveleducativo;
    }
    
    public void setTbniveleducativo(Tbniveleducativo tbniveleducativo) {
        this.tbniveleducativo = tbniveleducativo;
    }
    public Integer getMeta() {
        return this.meta;
    }
    
    public void setMeta(Integer meta) {
        this.meta = meta;
    }




}


