package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tbprogramacionexperienciasilaber generated by hbm2java
 */
public class Tbprogramacionexperienciasilaber  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcontenidosilaber tbcontenidosilaber;
     private Tbsilaber tbsilaber;
     private Date fechaProgramacion;
     private Set<Tbmapacompetenciassilaber> tbmapacompetenciassilabers = new HashSet<Tbmapacompetenciassilaber>(0);

    public Tbprogramacionexperienciasilaber() {
    }

	
    public Tbprogramacionexperienciasilaber(Integer consecutivo, Tbcontenidosilaber tbcontenidosilaber, Tbsilaber tbsilaber) {
        this.consecutivo = consecutivo;
        this.tbcontenidosilaber = tbcontenidosilaber;
        this.tbsilaber = tbsilaber;
    }
    public Tbprogramacionexperienciasilaber(Integer consecutivo, Tbcontenidosilaber tbcontenidosilaber, Tbsilaber tbsilaber, Date fechaProgramacion, Set<Tbmapacompetenciassilaber> tbmapacompetenciassilabers) {
       this.consecutivo = consecutivo;
       this.tbcontenidosilaber = tbcontenidosilaber;
       this.tbsilaber = tbsilaber;
       this.fechaProgramacion = fechaProgramacion;
       this.tbmapacompetenciassilabers = tbmapacompetenciassilabers;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcontenidosilaber getTbcontenidosilaber() {
        return this.tbcontenidosilaber;
    }
    
    public void setTbcontenidosilaber(Tbcontenidosilaber tbcontenidosilaber) {
        this.tbcontenidosilaber = tbcontenidosilaber;
    }
    public Tbsilaber getTbsilaber() {
        return this.tbsilaber;
    }
    
    public void setTbsilaber(Tbsilaber tbsilaber) {
        this.tbsilaber = tbsilaber;
    }
    public Date getFechaProgramacion() {
        return this.fechaProgramacion;
    }
    
    public void setFechaProgramacion(Date fechaProgramacion) {
        this.fechaProgramacion = fechaProgramacion;
    }
    public Set<Tbmapacompetenciassilaber> getTbmapacompetenciassilabers() {
        return this.tbmapacompetenciassilabers;
    }
    
    public void setTbmapacompetenciassilabers(Set<Tbmapacompetenciassilaber> tbmapacompetenciassilabers) {
        this.tbmapacompetenciassilabers = tbmapacompetenciassilabers;
    }




}


