package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final

import java.util.Date;

/**
 * Tbrutaexperienciaaprendizaje generated by hbm2java
 */
public class Tbrutaexperienciaaprendizaje  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcatalogoexperienciaaprendizaje tbcatalogoexperienciaaprendizaje;
     private Tbsilaber tbsilaber;
     private String codigo;
     private String descripcion;
     private String fechaCreacion;
     private String usuarioCreacion;
     private Integer consecutivoCtlgoPto;
     private String  descripcionCtlgoPto;
     private Date  fechaPosibleVisita;
     private Date fechaRealVisita ;
     private Integer estado;

    public Tbrutaexperienciaaprendizaje() {
    }

	
    public Tbrutaexperienciaaprendizaje(Integer consecutivo, Tbcatalogoexperienciaaprendizaje tbcatalogoexperienciaaprendizaje, Tbsilaber tbsilaber) {
        this.consecutivo = consecutivo;
        this.tbcatalogoexperienciaaprendizaje = tbcatalogoexperienciaaprendizaje;
        this.tbsilaber = tbsilaber;
        
    }
    public Tbrutaexperienciaaprendizaje(Integer consecutivo, Tbcatalogoexperienciaaprendizaje tbcatalogoexperienciaaprendizaje, Tbsilaber tbsilaber, String codigo, String descripcion, String fechaCreacion, String usuarioCreacion,Integer consecutivoCtlgoPto,String descripcionCtlgoPto, Date  fechaPosibleVisita, Date  fechaRealVisita, Integer estado) {
       this.consecutivo = consecutivo;
       this.tbcatalogoexperienciaaprendizaje = tbcatalogoexperienciaaprendizaje;
       this.tbsilaber = tbsilaber;
       this.codigo = codigo;
       this.descripcion = descripcion;
       this.fechaCreacion = fechaCreacion;
       this.usuarioCreacion = usuarioCreacion;
       this.consecutivoCtlgoPto = consecutivoCtlgoPto;
       this.descripcionCtlgoPto = descripcionCtlgoPto;
       this.fechaPosibleVisita = fechaPosibleVisita;
       this.fechaRealVisita = fechaRealVisita;
       this.estado = estado;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogoexperienciaaprendizaje getTbcatalogoexperienciaaprendizaje() {
        return this.tbcatalogoexperienciaaprendizaje;
    }
    
    public void setTbcatalogoexperienciaaprendizaje(Tbcatalogoexperienciaaprendizaje tbcatalogoexperienciaaprendizaje) {
        this.tbcatalogoexperienciaaprendizaje = tbcatalogoexperienciaaprendizaje;
    }
    public Tbsilaber getTbsilaber() {
        return this.tbsilaber;
    }
    
    public void setTbsilaber(Tbsilaber tbsilaber) {
        this.tbsilaber = tbsilaber;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getUsuarioCreacion() {
        return this.usuarioCreacion;
    }
    
    public void setUsuarioCreacion(String usuarioCreacion) {
        this.usuarioCreacion = usuarioCreacion;
    }


	public Integer getConsecutivoCtlgoPto() {
		return consecutivoCtlgoPto;
	}


	public void setConsecutivoCtlgoPto(Integer consecutivoCtlgoPto) {
		this.consecutivoCtlgoPto = consecutivoCtlgoPto;
	}


	public String getDescripcionCtlgoPto() {
		return descripcionCtlgoPto;
	}


	public void setDescripcionCtlgoPto(String descripcionCtlgoPto) {
		this.descripcionCtlgoPto = descripcionCtlgoPto;
	}


	public Date getFechaPosibleVisita() {
		return fechaPosibleVisita;
	}


	public void setFechaPosibleVisita(Date fechaPosibleVisita) {
		this.fechaPosibleVisita = fechaPosibleVisita;
	}


	public Date getFechaRealVisita() {
		return fechaRealVisita;
	}


	public void setFechaRealVisita(Date fechaRealVisita) {
		this.fechaRealVisita = fechaRealVisita;
	}


	public Integer getEstado() {
		return estado;
	}


	public void setEstado(Integer estado) {
		this.estado = estado;
	}




}


