package com.seit.silaba.modelo;
// Generated 19-jul-2017 6:40:16 by Hibernate Tools 4.3.1.Final



/**
 * Tbsociospuntosilaba generated by hbm2java
 */
public class Tbsociospuntosilaba  implements java.io.Serializable {


     private Integer consecutivo;
     private Tbcatalogopuntossilaba tbcatalogopuntossilaba;
     private Tbsocio tbsocio;

    public Tbsociospuntosilaba() {
    }

    public Tbsociospuntosilaba(Integer consecutivo, Tbcatalogopuntossilaba tbcatalogopuntossilaba, Tbsocio tbsocio) {
       this.consecutivo = consecutivo;
       this.tbcatalogopuntossilaba = tbcatalogopuntossilaba;
       this.tbsocio = tbsocio;
    }
   
    public Integer getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Integer consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Tbcatalogopuntossilaba getTbcatalogopuntossilaba() {
        return this.tbcatalogopuntossilaba;
    }
    
    public void setTbcatalogopuntossilaba(Tbcatalogopuntossilaba tbcatalogopuntossilaba) {
        this.tbcatalogopuntossilaba = tbcatalogopuntossilaba;
    }
    public Tbsocio getTbsocio() {
        return this.tbsocio;
    }
    
    public void setTbsocio(Tbsocio tbsocio) {
        this.tbsocio = tbsocio;
    }




}


